language: php

php:
  - '7.0'
  - '7.1'

# Configure environment to run test suites in parallel.
env:
  - TEST_SUITE = "Unit Tests"
  - TEST_SUITE = "Integration Tests"

# Install test coverage package.
install:
  - composer require satooshi/php-coveralls

# Install packages and create test coverage log directory.
before_script:
  - composer self-update
  - composer install --dev --no-interaction
  - mkdir -p build/logs

# Run tests and generate test coverage report.
script:
  - phpunit -d api_key=$API_KEY --testsuite "$TEST_SUITE" --coverage-clover build/logs/clover.xml

# Submit test coverage report to Coveralls.
after_success:
  - vendor/bin/coveralls -v

# Cache composer bits for faster test suite runs.
cache:
  directories:
  - $HOME/.composer/cache

notifications:
  email:
    on_success: change
    on_failure: always
